#!/usr/bin/env ruby

#
# generate some webpages from polar srd files
#

require 'find'
require 'time'
require 'date'
require 'optparse'
require 'fileutils'

class SrdInfo
    attr_accessor :time, :basename, :destdir, :text, :html
    attr_accessor :summary, :dist

    def parse(str)
        s = str.lines
        @summary = []
        @summary << s.grep(/Exercise duration:/)
        @summary << s.grep(/Exercise distance:/)
        @summary << "\n"
        @summary << s.grep(/Average heart rate:/)
        @summary << s.grep(/Maximum heart rate:/)
        @summary << "\n"
        @summary << s.grep(/Average speed:/)
        @summary << s.grep(/Maximum speed:/)
        @summary << "\n"
        @summary << s.grep(/Minimum altitude:/)
        @summary << s.grep(/Average altitude:/)
        @summary << s.grep(/Maximum altitude:/)
        @summary << s.grep(/Ascent:/)

        dist = s.grep(/Exercise distance:/).first
        if dist
            @dist = dist.split(':').last.to_f
        end
    end

    def to_s
        @summary.compact.join
    end
end

def html_img(file,alt)
    if File.exists?(file)
        "<img src=\"#{File.basename(file)}\" alt=\"#{alt}\" />"
    else
        ""
    end
end

STYLE='
<style type="text/css">
body {
  background-color: #FFFFFF;
  text-align:Center;
}

table.calendar {
  width: 100%;
  border-color: #000000;
  border-width: 5pt;
  border-style: Solid;
  text-align:Center;
  border-collapse: collapse;
  background-color: #FFFFFF;
  margin: 0px;
}

.monthcaption {
  /* background: URL(\'Caption.jpg\'); */
  background-color: #fe2400;
  background-color: #e85d5d;
  background-color: #e82a2a;
  font-family: Arial;
  font-size: 35pt;
  font-weight: Bold;
  font-style: Normal;
  color: #000000;
  text-decoration: None;
  border-color: #000000;
  border-width: 5pt;
  border-style: Solid;
  text-align: Right;
  padding: 5px;
  margin: -3px;
}

.weekdays {
  /* background: URL(\'Weekday.jpg\'); */
  background-color: #000000;
  background-color: #ffd866;
  background-color: #ffca2f;
  font-family: Arial;
  font-size: 14pt;
  font-weight: Normal;
  font-style: Normal;
  color: #000000;
  text-decoration: None;
  border-color: #000000;
  border-width: 1pt;
  border-style: Solid;
  text-align: Center;
}

.date {
  font-family: Arial;
  font-size: 12pt;
  font-weight: Bold;
  font-style: Normal;
  color: #000000;
  text-decoration: None;
  text-align: Left;
}

.events {
  font-family: Arial;
  font-size: 8pt;
  font-weight: Normal;
  font-style: Normal;
  color: #000000;
  text-decoration: None;
  border-color: #000000;
  border-width: 1pt;
  border-style: Solid;
  text-align: Left;
  padding: 5px;
  background-color: #FFFFFF;
}

/*
.itr:hover .bpop {	background-color: #FCFFE0; } 
.itr:hover .bpopleft {	background-color: #FCFFE0; } 
.itr:hover .bpopupright {	background-color: #FCFFE0; } 
.itr:hover .bpopupleft {	background-color: #FCFFE0; } 
*/

td.events a:link    { font-family:Arial; font-weight:Bold; color: #000000; font-size: 8pt; text-decoration: none;}
td.events a:visited { font-family:Arial; font-weight:Bold; color: #000000; font-size: 8pt; text-decoration: none;}
td.events a:hover   { font-family:Arial; font-weight:Bold; color: #000000; font-size: 8pt; text-decoration: none;}
td.events a:active  { font-family:Arial; font-weight:Bold; color: #000000; font-size: 8pt; text-decoration: none;}
td.events { font-family:Arial; font-weight:Bold; color: #000000; font-size: 8pt; text-decoration: none;}
td.events .dt { font-family:Arial; font-weight:Normal; color: #808080; font-size: 7pt; font-style: Normal; }

.bpop {
    display: none;
    font-size: 8pt;
    text-decoration: none;
    z-index : auto;
    text-decoration: none;
}

a.itr:hover {
    border-width: 0; /* IE */
    color: #000;
    font-size: 8pt;  
    z-index : 1004;
    text-decoration: none;
    position: relative;
}
 
.itr {
    text-decoration: none;
    color: #000;      
    font-size: 8pt;
    z-index : 0; 
    width:98%;
}

.itr:active { 
    font-size: 8pt;
    color: black;
    font-weight: normal; 
    text-decoration: none;  
    z-index : 1001;     
   
}

.itr:link { 
    font-size: 8pt;
    font-weight: normal; 
    color: black;
    text-decoration: none;   
    z-index : 1002;
}

.itr:visited { 
   
    font-size: 8pt;
    color: black;
    font-weight: normal;     
    z-index : 1003;
    text-decoration: none;
}

.itr:hover {
    text-decoration: none;
}

.itr:hover .bpop {
    display: block;
    position: absolute;
    background-color: #FCFFE0;
    padding: 5px 5px 5px 5px;
    border: 1px #000 solid;
    white-space: normal;
    width : 35em;
    font-size: 8pt;
    left: -15em;
    top: 2.5em;
    text-align : center;
    text-decoration: none;
    z-index : 1005;
} 
</style>'

PLOT_DIST = '
set terminal pngcairo enhanced size 700, 700;
set output "@OUT@";
set tmargin 0;
set bmargin 1;
set lmargin 5;
set rmargin 5;
set multiplot layout 4,1 title "@TITLE@\n";
set origin 1,1;
min=4000;
max=0;
grab(x)=(x<min)?min=x:(x>max)?max=x:0;
plot "@IN@" using 3:(grab($3));
set key autotitle column nobox samplen 1;
set grid;
set origin 0,0.56;
set size 1, 0.36;
set yrange [80:200];
set xtics nomirror format "";
set ytics 10 nomirror;
rgb(r,g,b) = 65536 * int(r) + 256 * int(g) + int(b);
plot "" using 6:($2>80 ? $2 :1/0) title "HR" with lines lc rgb "dark-red";
set yrange [*:*];
set origin 0,0.33;
set xtics nomirror format "";
set ytics 10 nomirror;
plot "" using 6:5 title "Speed" with lines lc rgb "dark-blue";
set origin 0,0.1;
set xtics nomirror format "%g";
set ytics 100 nomirror;
plot "" using 6:3:(rgb(0,(($3-min)/(max-min)*255),0)) title "Alt" with lines lc rgb variable;'

# PLOT_TIME = '
# set terminal pngcairo enhanced size 700, 700;
# set output "@OUT@";
# set tmargin 0;
# set bmargin 1;
# set lmargin 5;
# set rmargin 5;
# set multiplot layout 4,1 title "@TITLE@\n";
# set origin 1,1;
# min=4000;
# max=0;
# grab(x)=(x<min)?min=x:(x>max)?max=x:0;
# plot "@IN@" using 3:(grab($3));
# set key autotitle column nobox samplen 1;
# set grid;
# set origin 0,0.56;
# set size 1, 0.36;
# set yrange [80:200];
# set timefmt "%H:%M:%S";
# set xdata time;
# set xtics nomirror format "";
# set ytics 10 nomirror;
# rgb(r,g,b) = 65536 * int(r) + 256 * int(g) + int(b);
# plot "" using 1:($2>80 ? $2 :1/0) title "HR" with lines lc rgb "dark-red";
# set yrange [*:*];
# set origin 0,0.33;
# set xtics nomirror format "";
# set ytics 10 nomirror;
# plot "" using 1:5 title "Speed" with lines lc rgb "dark-blue";
# set origin 0,0.1;
# set xtics nomirror format "%g";
# set ytics 100 nomirror;
# plot "" using 1:3:(rgb(0,(($3-min)/(max-min)*255),0)) title "Alt" with lines lc rgb variable;
# '

PLOT_TIME = '
set terminal pngcairo enhanced size 700, 700;
set output "@OUT@";
set tmargin 0;
set bmargin 1;
set lmargin 5;
set rmargin 5;
set multiplot layout 4,1 title "@TITLE@\n";
set origin 1,1;
min=4000;
max=0;
grab(x)=(x<min)?min=x:(x>max)?max=x:0;
plot "@IN@" using 3:(grab($3));
set key autotitle column nobox samplen 1;
set grid;
set origin 0,0.56;
set size 1, 0.36;
set yrange [80:200];
set timefmt "%H:%M:%S";
set xdata time;
set xtics nomirror format "";
set ytics 10 nomirror;
rgb(r,g,b) = 65536 * int(r) + 256 * int(g) + int(b);
plot "" using 1:($2>80 ? $2 :1/0) title "HR" with lines lc rgb "dark-red";
set yrange [*:*];
set origin 0,0.33;
set xtics nomirror format "";
set ytics 10 nomirror;
plot "" using 1:5 title "Speed" with lines lc rgb "dark-blue";
set origin 0,0.1;
set xtics nomirror format "%g";
set ytics 100 nomirror;
plot "" using 1:3:(rgb(0,(($3-min)/(max-min)*255),0)) title "Alt" with lines lc rgb variable;
'

def process_txt(txt, dest)
    puts "processing #{txt}"
    info = SrdInfo.new
    info.basename = File.basename(txt, ".txt")
    info.time = Time.parse(info.basename.split('.').first)
    info.destdir  = "#{dest}/#{info.time.strftime("%Y%m")}/"
    info.html = info.destdir + "/" + info.basename + ".html"

    data = File.read(txt)
    info.parse(data)

    if not File.directory? info.destdir
        FileUtils.mkdir_p info.destdir
    end

    if (File.exists?(info.html)) and false
        return info
    end

    plotcmd = PLOT_TIME.dup.gsub("@IN@", txt).gsub("@OUT@", info.basename + "-time.png").gsub("@TITLE@", "Time")
    command = "cd #{info.destdir}; gnuplot -e '#{plotcmd}'"
    system(command)
    if info.dist > 0
        plotcmd = PLOT_DIST.dup.gsub("@IN@", txt).gsub("@OUT@", info.basename + "-dist.png").gsub("@TITLE@", "Distance")
        command = "cd #{info.destdir}; gnuplot -e '#{plotcmd}'"
        system(command)
    end

    File.open(info.html, "w") do | h |
        h.puts html_head(info.basename)
        h.puts "<h1>#{info.time}</h1>"
        h.puts "<h2>Summary</h2>"
        h.puts "<pre>"
        h.puts info.to_s
        h.puts "</pre>"
        if false
        h.puts "<h2>Histogram</h2>"
        h.puts "<p>"
        s = ".hr.h.png"; h.puts html_img(info.destdir + "/" + info.basename + s, s)
        s = ".hr.z.png"; h.puts html_img(info.destdir + "/" + info.basename + s, s)
        h.puts "</p>"
        end
        if info.dist > 0
            h.puts "<h2>Distance</h2>"
            h.puts "<p>"
            s = ".png"; h.puts html_img(info.destdir + "/" + info.basename + "-dist.png", s)
            h.puts "</p>"
        end
        h.puts "<h2>Time</h2>"
        h.puts "<p>"
        s = ".png"; h.puts html_img(info.destdir + "/" + info.basename + "-time.png", s)
        h.puts "</p>"
        h.puts html_foot()
    end
    return info
end

def html_head(title, opt={})
    h = []
    h << '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
    h << '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">'
    h << '<head>'
    h << '<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />'
    h << '<title>' + title + '</title>'
    h << opt[:head] if opt[:head]
    h << '</head><body>'
    h.join("\n")
end

def html_foot()
    h = []
    h << '</body></html>'
    h.join("\n")
end    

def generate_overview(overview, path)
    File.open(path + "/index.html", "w") do | f |
        title = "Polar Overview"
        f.puts html_head(title)
        f.puts "<h1>#{title}</h1>"
        f.puts "<ul>"
        overview.each do | o |
            f.puts "<li><a href=\"#{o.last}\">#{o.first}</a></li>"
        end
        f.puts "</ul>"
        f.puts html_foot()
    end
end

def generate_index(info)
    result = []
    container = {}
    info.each do | i |
        if not container[i.destdir]
            container[i.destdir] = []
        end
        container[i.destdir] << i
    end
    # puts "container: #{container.inspect}"
    container.keys.sort.each do | dir |
        index_path = dir + "/index.html"
        puts "generating index: #{index_path}"
        File.open(index_path, "w") do | index |
            entries = {}
            month = container[dir].first.time.month
            year  = container[dir].first.time.year
            container[dir].each do | i |
                entries[i.time.day] ||= []
                entries[i.time.day] << '<a class="itr"  href="' + i.basename + '.html">' + 
                    '<b>' + i.time.strftime("%H:%M") + '</b>' + 
                    '<span class="bpop" style="left:-6em; width:16em; top:-4.5em; ">' + 
                    'Workout: ' + i.time.strftime("%H:%M") + '<br/>' + 
                    i.text.to_s + '<br/></span></a>'

            end
            title = "#{Date::MONTHNAMES[month]} #{year}"
            index.puts html_head(title, :head => STYLE)
            index.puts generate_calendar(year, month, entries)
            index.puts html_foot()
            result << [title, index_path]
        end
    end
    result
end

def generate_calendar(year,month,entries={})
    firstwday = Date.civil(year,month,1).wday
    lastday   = (Date.civil(year,(month + 1) % 12,1) - 1).day
    c = []

    c << '<table class="calendar" cellspacing="0">'
    c << "<caption class=\"monthcaption\"> #{Date::MONTHNAMES[month]} #{year}</caption>"

    # header
    c << "<tr>"
    ths = '<th style="width: 14%;" valign="middle" align="center" class="weekdays">'
    the = '</th>'
    c << ths + Date::DAYNAMES[0] + the 
    c << ths + Date::DAYNAMES[1] + the
    c << ths + Date::DAYNAMES[2] + the
    c << ths + Date::DAYNAMES[3] + the
    c << ths + Date::DAYNAMES[4] + the
    c << ths + Date::DAYNAMES[5] + the
    c << ths + Date::DAYNAMES[6] + the
    c << "</tr>"

    cellcount = 1
    daycount = 1
    loop do
        c << '<tr class="events">'
        # generate row
        1.upto(7) do | wday |
            # generate cell
            if (cellcount > firstwday and daycount <= lastday)
                if [1,7].include?(wday)
                    c << '<td class="events" valign="top" align="left" style="background-color:#FFFFEC;">'
                    color='color:#C00000;'
                else
                    c << '<td class="events" valign="top" align="left">'
                    color='color:#000000;'
                end
                if entries[daycount]
                    bold = "font-weight:bold;"
                else
                    bold = ""
                end
                c << '<div class="date">' + daycount.to_s + '</div><br />'
                if entries[daycount]
                    content = entries[daycount]
                    content = [content] if content.class == String
                    0.upto 2 do | i |
                        c << content[i].to_s + '<br />'
                    end
                else
                    c << '<br /><br /><br />'
                end
                daycount += 1
            else
                c << '<td class="events" valign="top" align="left" style="background-color:#E9E9E9;">'
                c << '&nbsp;<br /><br /><br /><br />'
            end
            c << '</td>'
            cellcount += 1
        end
        c << '</tr>'
        break if daycount > lastday
    end
    c << "</table>"
    return c.join("\n")
end

OPT = {}
OPT[:print] = false


ARGV.options do | opts |
    opts.banner = "Usage: s725html [options]"
	opts.on("-s SOURCE", "source directory") do | arg |
        OPT[:source] = arg
    end
	opts.on("-d DEST", "destination directory") do | arg |
        OPT[:dest] = arg
    end
	opts.on("-h", "print help") do 
		puts opts
		exit
	end
end

ARGV.parse!

if OPT[:source]
    source = OPT[:source] 
else
    source = Dir.pwd
end

if OPT[:dest]
    dest = File.expand_path(OPT[:dest])
else
    dest = Dir.pwd
end

info = []
Find.find(source) do | file |
    next unless File.file?(file)
    next unless file =~ /\.txt$/
    file = File.expand_path(file)
    info << process_txt(file, dest)
end
overview = generate_index(info)
generate_overview(overview, dest)
